

services:

#  mongodb:
#   image: mongo:7.0
#    container_name: mongodb
#    env_file: ./.env
#    ports:
#      - "${MONGO_PORT}:${MONGO_PORT}"
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT}/test --quiet
#      interval: 10s
#      timeout: 5s
#      retries: 5

  app:
    restart: on-failure
    image: muvio
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT:-10000}/quick-health" ]
      interval: 10s
      timeout: 5s
      retries: 40
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.data.mongodb.uri": "${MONGO_URL}",
          "tmdb.api.key": "${TMDB_API_TOKEN}"
        }
      JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
